import type { Slot } from '@/api/types';
import { cn } from '@/lib/utils';

type Props = {
  imageUrl: string;
  imageSize: [number, number];
  cols: number;
  slots: Slot[];
};

/**
 * Live thumbnails of each slot polygon, rendered client-side via SVG clipping.
 * Updates immediately as the user drags. The proper warped crop is generated by
 * the backend at commit time.
 */
export function SlotThumbnails({ imageUrl, imageSize, cols, slots }: Props) {
  return (
    <div
      className="grid gap-2"
      style={{ gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` }}
    >
      {slots.map((s) => (
        <SlotThumb key={s.slot_index} imageUrl={imageUrl} imageSize={imageSize} slot={s} />
      ))}
    </div>
  );
}

function SlotThumb({
  imageUrl,
  imageSize,
  slot,
}: {
  imageUrl: string;
  imageSize: [number, number];
  slot: Slot;
}) {
  if (slot.disabled) {
    return (
      <div className="relative aspect-card rounded-md border-2 border-dashed border-border bg-muted/40 flex flex-col items-center justify-center text-muted-foreground text-sm gap-1">
        <span>{slot.slot_index + 1}</span>
        <span className="text-xs">empty</span>
      </div>
    );
  }
  const [imgW, imgH] = imageSize;
  const xs = slot.polygon.map((p) => p.x);
  const ys = slot.polygon.map((p) => p.y);
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  const maxX = Math.max(...xs);
  const maxY = Math.max(...ys);
  const w = Math.max(1, maxX - minX);
  const h = Math.max(1, maxY - minY);
  const points = slot.polygon.map((p) => `${p.x},${p.y}`).join(' ');
  const clipId = `clip-thumb-${slot.slot_index}`;
  return (
    <div
      className={cn(
        'relative aspect-card rounded-md border-2 overflow-hidden bg-card',
        // Provenance palette: blue = refined geometry, amber = unconfirmed proposal.
        slot.refined ? 'border-info/70' : 'border-warning/70',
      )}
    >
      <svg
        viewBox={`${minX} ${minY} ${w} ${h}`}
        preserveAspectRatio="xMidYMid slice"
        className="block w-full h-full"
      >
        <defs>
          <clipPath id={clipId}>
            <polygon points={points} />
          </clipPath>
        </defs>
        <image href={imageUrl} width={imgW} height={imgH} clipPath={`url(#${clipId})`} />
      </svg>
      <span className="absolute top-1 left-1 px-1.5 py-0.5 rounded bg-background/80 text-xs text-foreground">
        {slot.slot_index + 1}
      </span>
    </div>
  );
}
