import type { Slot } from './types';

type Props = {
  imageUrl: string;
  imageSize: [number, number];
  slots: Slot[];
};

/**
 * Live thumbnails of each slot polygon, rendered client-side via SVG clipping.
 * Updates immediately when the user drags. No perspective warp — just shows the
 * polygon's region of the source image. The proper warped crop is generated by
 * the backend at commit time.
 */
export function SlotThumbnails({ imageUrl, imageSize, slots }: Props) {
  return (
    <div className="thumbs">
      {slots.map((s) => (
        <SlotThumb key={s.slot_index} imageUrl={imageUrl} imageSize={imageSize} slot={s} />
      ))}
    </div>
  );
}

function SlotThumb({
  imageUrl,
  imageSize,
  slot,
}: {
  imageUrl: string;
  imageSize: [number, number];
  slot: Slot;
}) {
  if (slot.disabled) {
    return (
      <div className="thumb thumb-empty">
        <span>{slot.slot_index + 1}</span>
        <span className="empty-label">empty</span>
      </div>
    );
  }
  const [imgW, imgH] = imageSize;
  const xs = slot.polygon.map((p) => p.x);
  const ys = slot.polygon.map((p) => p.y);
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  const maxX = Math.max(...xs);
  const maxY = Math.max(...ys);
  const w = Math.max(1, maxX - minX);
  const h = Math.max(1, maxY - minY);
  const points = slot.polygon.map((p) => `${p.x},${p.y}`).join(' ');
  const clipId = `clip-thumb-${slot.slot_index}`;
  return (
    <div className={`thumb ${slot.refined ? 'refined' : 'unrefined'}`}>
      <svg
        viewBox={`${minX} ${minY} ${w} ${h}`}
        preserveAspectRatio="xMidYMid slice"
        style={{ width: '100%', height: '100%', display: 'block' }}
      >
        <defs>
          <clipPath id={clipId}>
            <polygon points={points} />
          </clipPath>
        </defs>
        <image href={imageUrl} width={imgW} height={imgH} clipPath={`url(#${clipId})`} />
      </svg>
      <span className="thumb-label">{slot.slot_index + 1}</span>
    </div>
  );
}
