"""Multi-page PDF export of the card database — Discord-shareable, printable.

Layout per page:

  +---------------------------------------------------------------+
  |  Card Tracker — Collection                                    |
  |  N cards · YYYY-MM-DD · X pokémon · Y sports · Z other        |
  +---------------------------------------------------------------+
  |  +-------+   Card Name                                        |
  |  | thumb |   Set · #123 · 2024                                |
  |  |       |   POKEMON                                          |
  |  +-------+   notes if any                                     |
  +---------------------------------------------------------------+
  |  Generated by 10pow6 Card Tracker        Page 1 / N           |
  +---------------------------------------------------------------+

Single PDF, multiple pages. Pillow saves each page as a JPEG-encoded image
inside the PDF for compact file size — typically ~10–20 KB per card row.
"""
from __future__ import annotations

from contextlib import closing
from datetime import datetime
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from card_tracker.db.engine import connect
from card_tracker.services.paths import from_relative


# Page dimensions: 150 DPI A4.
PAGE_W = 1240
PAGE_H = 1754
MARGIN = 60
HEADER_H = 130
FOOTER_H = 50
THUMB_W = 220
THUMB_H = round(THUMB_W * 88 / 63)  # 307 — trading-card aspect
THUMB_RADIUS = 14
ROW_H = THUMB_H + 24  # auto-fits the thumbnail + breathing padding
ROW_GAP = 12

# Theme — clean light catalog.
BG = (250, 250, 252)
PANEL = (255, 255, 255)
BORDER = (228, 228, 234)
FG = (24, 24, 28)
MUTED = (120, 120, 130)
ACCENT = (60, 90, 200)

# Rows per page derived from the layout constants.
_CONTENT_H = PAGE_H - HEADER_H - FOOTER_H - 2 * MARGIN
ROWS_PER_PAGE = max(1, _CONTENT_H // (ROW_H + ROW_GAP))


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    """Best-effort cross-platform font loader. Falls back to PIL's default bitmap font."""
    candidates = [
        # Windows
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        # macOS
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
        if bold
        else "/System/Library/Fonts/Supplemental/Arial.ttf",
        # Linux
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
        if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for p in candidates:
        try:
            return ImageFont.truetype(p, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _round_thumb(img: Image.Image, w: int, h: int, radius: int) -> Image.Image:
    img = img.convert("RGB").resize((w, h), Image.LANCZOS)
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, w, h), radius=radius, fill=255)
    out = Image.new("RGB", (w, h), PANEL)
    out.paste(img, (0, 0), mask)
    return out


def _placeholder_thumb(w: int, h: int) -> Image.Image:
    img = Image.new("RGB", (w, h), BORDER)
    draw = ImageDraw.Draw(img)
    f = _font(14)
    msg = "no image"
    bbox = draw.textbbox((0, 0), msg, font=f)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(((w - tw) / 2, (h - th) / 2), msg, fill=MUTED, font=f)
    return img


def _draw_truncated(
    draw: ImageDraw.ImageDraw,
    xy: tuple[int, int],
    text: str,
    font,
    max_width: int,
    fill,
) -> None:
    if not text:
        return
    if draw.textlength(text, font=font) <= max_width:
        draw.text(xy, text, fill=fill, font=font)
        return
    ellipsis = "…"
    e_w = draw.textlength(ellipsis, font=font)
    while text and draw.textlength(text, font=font) + e_w > max_width:
        text = text[:-1]
    draw.text(xy, text + ellipsis, fill=fill, font=font)


def _render_card_row(
    img: Image.Image,
    draw: ImageDraw.ImageDraw,
    x: int,
    y: int,
    w: int,
    card: dict,
) -> None:
    # Panel background
    draw.rounded_rectangle(
        (x, y, x + w, y + ROW_H), radius=14, outline=BORDER, fill=PANEL, width=1
    )

    # Thumbnail
    pad = (ROW_H - THUMB_H) // 2
    thumb_x, thumb_y = x + pad, y + pad
    rep = card.get("rep_path")
    pasted = False
    if rep:
        try:
            with Image.open(from_relative(rep)) as im:
                img.paste(_round_thumb(im, THUMB_W, THUMB_H, THUMB_RADIUS), (thumb_x, thumb_y))
                pasted = True
        except (FileNotFoundError, OSError):
            pass
    if not pasted:
        img.paste(_placeholder_thumb(THUMB_W, THUMB_H), (thumb_x, thumb_y))

    # Metadata
    text_x = thumb_x + THUMB_W + 24
    text_w = w - (text_x - x) - pad
    title_font = _font(28, bold=True)
    sub_font = _font(18)
    type_font = _font(14, bold=True)
    notes_font = _font(14)

    name = card.get("name") or "(unnamed)"
    name_color = FG if card.get("name") else MUTED
    cur_y = y + pad
    _draw_truncated(draw, (text_x, cur_y), name, title_font, text_w, name_color)
    cur_y += 42

    sub_parts = [
        card.get("set_name"),
        card.get("card_number"),
        str(card["year"]) if card.get("year") else None,
    ]
    sub = " · ".join(p for p in sub_parts if p) or "—"
    _draw_truncated(draw, (text_x, cur_y), sub, sub_font, text_w, MUTED)
    cur_y += 28

    type_label = (card.get("card_type") or "").upper()
    if type_label:
        _draw_truncated(draw, (text_x, cur_y), type_label, type_font, text_w, ACCENT)
        cur_y += 22

    notes = card.get("notes")
    if notes:
        _draw_truncated(draw, (text_x, cur_y), notes, notes_font, text_w, MUTED)


def _render_page(
    chunk: list[dict], page_num: int, total_pages: int, summary: dict
) -> Image.Image:
    img = Image.new("RGB", (PAGE_W, PAGE_H), BG)
    draw = ImageDraw.Draw(img)

    # Header
    draw.text((MARGIN, MARGIN), "Card Tracker — Collection", fill=FG, font=_font(36, bold=True))
    summary_text = (
        f"{summary['count']} cards · {summary['date']} · "
        f"{summary['pokemon']} pokémon · {summary['sports']} sports · {summary['other']} other"
    )
    draw.text((MARGIN, MARGIN + 50), summary_text, fill=MUTED, font=_font(16))
    line_y = MARGIN + HEADER_H - 10
    draw.line(((MARGIN, line_y), (PAGE_W - MARGIN, line_y)), fill=BORDER, width=2)

    # Card rows
    content_y = MARGIN + HEADER_H + 10
    row_w = PAGE_W - 2 * MARGIN
    for i, card in enumerate(chunk):
        _render_card_row(img, draw, MARGIN, content_y + i * (ROW_H + ROW_GAP), row_w, card)

    if not chunk:
        empty_font = _font(20)
        draw.text(
            (MARGIN, content_y + 40),
            "No cards yet — scan a binder page to start your collection.",
            fill=MUTED,
            font=empty_font,
        )

    # Footer
    foot_font = _font(13)
    foot_y = PAGE_H - MARGIN - 18
    draw.text((MARGIN, foot_y), "Generated by 10pow6 Card Tracker", fill=MUTED, font=foot_font)
    page_text = f"Page {page_num} / {total_pages}"
    draw.text(
        (PAGE_W - MARGIN - draw.textlength(page_text, font=foot_font), foot_y),
        page_text,
        fill=MUTED,
        font=foot_font,
    )

    return img


def _row_to_card_dict(r) -> dict:
    return {
        "id": r["id"],
        "name": r["name"],
        "set_name": r["set_name"],
        "card_number": r["card_number"],
        "year": r["year"],
        "card_type": r["card_type"],
        "notes": r["notes"],
        "rep_path": r["representative_crop_path"],
    }


def _fetch_cards() -> list[dict]:
    sql = """
    SELECT id, name, set_name, card_number, year, card_type, notes,
           representative_crop_path
    FROM core_card
    ORDER BY
      CASE WHEN name IS NULL THEN 1 ELSE 0 END,
      LOWER(COALESCE(name, '')),
      LOWER(COALESCE(set_name, '')),
      card_number,
      created_at
    """
    with closing(connect()) as conn:
        rows = conn.execute(sql).fetchall()
    return [_row_to_card_dict(r) for r in rows]


def _fetch_cards_for_binder(binder_id: str) -> list[dict]:
    sql = """
    SELECT DISTINCT c.id, c.name, c.set_name, c.card_number, c.year, c.card_type,
           c.notes, c.representative_crop_path
    FROM core_card c
    JOIN placement pl ON pl.core_card_id = c.id
    JOIN page p       ON pl.page_id = p.id
    WHERE p.binder_id = ?
    ORDER BY
      CASE WHEN c.name IS NULL THEN 1 ELSE 0 END,
      LOWER(COALESCE(c.name, '')),
      LOWER(COALESCE(c.set_name, '')),
      c.card_number,
      c.created_at
    """
    with closing(connect()) as conn:
        rows = conn.execute(sql, (binder_id,)).fetchall()
    return [_row_to_card_dict(r) for r in rows]


def _summarize(cards: list[dict]) -> dict:
    counts = {"pokemon": 0, "sports": 0, "other": 0}
    for c in cards:
        t = (c.get("card_type") or "other").lower()
        counts[t if t in counts else "other"] += 1
    return {
        "count": len(cards),
        "date": datetime.utcnow().strftime("%Y-%m-%d"),
        **counts,
    }


def _save_pdf(pages: list[Image.Image], out_path: Path) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pages[0].save(
        out_path,
        save_all=True,
        append_images=pages[1:],
        format="PDF",
        resolution=150.0,
    )
    return out_path


def _render_card_list_pdf(cards: list[dict], summary: dict, out_path: Path) -> Path:
    chunks = [cards[i : i + ROWS_PER_PAGE] for i in range(0, len(cards), ROWS_PER_PAGE)] or [[]]
    pages = [
        _render_page(chunk, i + 1, len(chunks), summary) for i, chunk in enumerate(chunks)
    ]
    return _save_pdf(pages, out_path)


def render_collection_pdf(out_path: Path) -> Path:
    """Render every CORE row to a multi-page PDF at `out_path`. Returns the path."""
    cards = _fetch_cards()
    return _render_card_list_pdf(cards, _summarize(cards), out_path)


def render_binder_cards_pdf(binder_id: str, binder_name: str, out_path: Path) -> Path:
    """Render the cards belonging to one binder as a row-style multi-page PDF."""
    cards = _fetch_cards_for_binder(binder_id)
    summary = _summarize(cards)
    summary["binder_name"] = binder_name
    return _render_card_list_pdf(cards, summary, out_path)


# ---- Binder pages PDF (one PDF page per binder page, full RxC grid) ----

GRID_GAP = 18
SLOT_CAPTION_GAP = 8
SLOT_CAPTION_LINES = 2
CARD_RADIUS = 12


def _fit_card_size(cell_w: int, cell_h: int, caption_h: int) -> tuple[int, int]:
    """Largest 63:88 card that fits inside a cell after reserving caption height."""
    avail_h = cell_h - caption_h - SLOT_CAPTION_GAP
    by_w_h = round(cell_w * 88 / 63)
    if by_w_h <= avail_h:
        return cell_w, by_w_h
    return round(avail_h * 63 / 88), avail_h


def _fetch_binder_pages(binder_id: str) -> list[dict]:
    """Return one dict per binder page with the placements + linked card metadata
    needed to render a full-grid PDF page. Empty/unmatched slots are returned as
    placement entries with `crop_path=None` so the renderer can draw an outline.
    """
    pages_sql = """
    SELECT id, page_number FROM page
    WHERE binder_id = ?
    ORDER BY page_number ASC
    """
    placements_sql = """
    SELECT pl.slot_index, pl.crop_image_path, pl.review_status,
           c.name, c.set_name, c.card_number, c.year
    FROM placement pl
    LEFT JOIN core_card c ON pl.core_card_id = c.id
    WHERE pl.page_id = ?
    ORDER BY pl.slot_index
    """
    with closing(connect()) as conn:
        page_rows = conn.execute(pages_sql, (binder_id,)).fetchall()
        result = []
        for pr in page_rows:
            slots = conn.execute(placements_sql, (pr["id"],)).fetchall()
            result.append({
                "page_number": pr["page_number"],
                "placements": [
                    {
                        "slot_index": s["slot_index"],
                        "crop_path": s["crop_image_path"],
                        "review_status": s["review_status"],
                        "name": s["name"],
                        "set_name": s["set_name"],
                        "card_number": s["card_number"],
                        "year": s["year"],
                    }
                    for s in slots
                ],
            })
    return result


def _render_slot(
    img: Image.Image,
    draw: ImageDraw.ImageDraw,
    cell_x: int,
    cell_y: int,
    cell_w: int,
    cell_h: int,
    placement: dict | None,
) -> None:
    caption_h = 36
    card_w, card_h = _fit_card_size(cell_w, cell_h, caption_h)
    card_x = cell_x + (cell_w - card_w) // 2
    card_y = cell_y

    crop = placement.get("crop_path") if placement else None
    pasted = False
    if crop:
        try:
            with Image.open(from_relative(crop)) as im:
                img.paste(_round_thumb(im, card_w, card_h, CARD_RADIUS), (card_x, card_y))
                pasted = True
        except (FileNotFoundError, OSError):
            pass
    if not pasted:
        draw.rounded_rectangle(
            (card_x, card_y, card_x + card_w, card_y + card_h),
            radius=CARD_RADIUS,
            outline=BORDER,
            fill=PANEL,
            width=2,
        )
        empty_font = _font(14)
        msg = "empty"
        tw = draw.textlength(msg, font=empty_font)
        draw.text(
            (card_x + (card_w - tw) // 2, card_y + card_h // 2 - 8),
            msg,
            fill=MUTED,
            font=empty_font,
        )

    name_font = _font(13, bold=True)
    sub_font = _font(11)
    cap_y = card_y + card_h + SLOT_CAPTION_GAP
    name = (placement or {}).get("name") or ""
    if name:
        _draw_truncated(draw, (cell_x, cap_y), name, name_font, cell_w, FG)
        sub_parts = [
            (placement or {}).get("set_name"),
            (placement or {}).get("card_number"),
            str((placement or {}).get("year")) if (placement or {}).get("year") else None,
        ]
        sub = " · ".join(p for p in sub_parts if p)
        if sub:
            _draw_truncated(draw, (cell_x, cap_y + 16), sub, sub_font, cell_w, MUTED)


def _render_binder_page(
    binder_name: str,
    layout_str: str,
    rows: int,
    cols: int,
    page_data: dict,
    page_num: int,
    total_pages: int,
) -> Image.Image:
    img = Image.new("RGB", (PAGE_W, PAGE_H), BG)
    draw = ImageDraw.Draw(img)

    # Header
    draw.text((MARGIN, MARGIN), binder_name, fill=FG, font=_font(34, bold=True))
    sub = f"Binder · {layout_str} · Page {page_data['page_number']}"
    draw.text((MARGIN, MARGIN + 46), sub, fill=MUTED, font=_font(16))
    line_y = MARGIN + HEADER_H - 10
    draw.line(((MARGIN, line_y), (PAGE_W - MARGIN, line_y)), fill=BORDER, width=2)

    # Grid
    grid_x = MARGIN
    grid_y = MARGIN + HEADER_H + 10
    grid_w = PAGE_W - 2 * MARGIN
    grid_h = PAGE_H - grid_y - MARGIN - FOOTER_H
    cell_w = (grid_w - GRID_GAP * (cols - 1)) // cols
    cell_h = (grid_h - GRID_GAP * (rows - 1)) // rows

    by_index = {p["slot_index"]: p for p in page_data["placements"]}
    for slot in range(rows * cols):
        r, c = divmod(slot, cols)
        cx = grid_x + c * (cell_w + GRID_GAP)
        cy = grid_y + r * (cell_h + GRID_GAP)
        _render_slot(img, draw, cx, cy, cell_w, cell_h, by_index.get(slot))

    # Footer
    foot_font = _font(13)
    foot_y = PAGE_H - MARGIN - 18
    draw.text((MARGIN, foot_y), "Generated by 10pow6 Card Tracker", fill=MUTED, font=foot_font)
    page_text = f"Page {page_num} / {total_pages}"
    draw.text(
        (PAGE_W - MARGIN - draw.textlength(page_text, font=foot_font), foot_y),
        page_text,
        fill=MUTED,
        font=foot_font,
    )
    return img


def render_binder_pages_pdf(
    binder_id: str,
    binder_name: str,
    layout_str: str,
    rows: int,
    cols: int,
    out_path: Path,
) -> Path:
    """Render each binder page as a full RxC card grid, one PDF page per binder page."""
    page_data = _fetch_binder_pages(binder_id)
    if not page_data:
        # Single empty page so the file is still valid.
        img = Image.new("RGB", (PAGE_W, PAGE_H), BG)
        draw = ImageDraw.Draw(img)
        draw.text((MARGIN, MARGIN), binder_name, fill=FG, font=_font(34, bold=True))
        draw.text(
            (MARGIN, MARGIN + 60),
            "No pages scanned yet.",
            fill=MUTED,
            font=_font(18),
        )
        return _save_pdf([img], out_path)

    total = len(page_data)
    images = [
        _render_binder_page(binder_name, layout_str, rows, cols, pd, i + 1, total)
        for i, pd in enumerate(page_data)
    ]
    return _save_pdf(images, out_path)
