"""Multi-page PDF export of the card database — Discord-shareable, printable.

Layout per page:

  +---------------------------------------------------------------+
  |  Card Tracker — Collection                                    |
  |  N cards · YYYY-MM-DD · X pokémon · Y sports · Z other        |
  +---------------------------------------------------------------+
  |  +-------+   Card Name                                        |
  |  | thumb |   Set · #123 · 2024                                |
  |  |       |   POKEMON                                          |
  |  +-------+   notes if any                                     |
  +---------------------------------------------------------------+
  |  Generated by 10pow6 Card Tracker        Page 1 / N           |
  +---------------------------------------------------------------+

Single PDF, multiple pages. Pillow saves each page as a JPEG-encoded image
inside the PDF for compact file size — typically ~10–20 KB per card row.
"""
from __future__ import annotations

from contextlib import closing
from datetime import datetime
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from card_tracker.db.engine import connect
from card_tracker.services.paths import from_relative


# Page dimensions: 150 DPI A4.
PAGE_W = 1240
PAGE_H = 1754
MARGIN = 60
HEADER_H = 130
FOOTER_H = 50
THUMB_W = 220
THUMB_H = round(THUMB_W * 88 / 63)  # 307 — trading-card aspect
THUMB_RADIUS = 14
ROW_H = THUMB_H + 24  # auto-fits the thumbnail + breathing padding
ROW_GAP = 12

# Theme — clean light catalog.
BG = (250, 250, 252)
PANEL = (255, 255, 255)
BORDER = (228, 228, 234)
FG = (24, 24, 28)
MUTED = (120, 120, 130)
ACCENT = (60, 90, 200)

# Rows per page derived from the layout constants.
_CONTENT_H = PAGE_H - HEADER_H - FOOTER_H - 2 * MARGIN
ROWS_PER_PAGE = max(1, _CONTENT_H // (ROW_H + ROW_GAP))


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    """Best-effort cross-platform font loader. Falls back to PIL's default bitmap font."""
    candidates = [
        # Windows
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        # macOS
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
        if bold
        else "/System/Library/Fonts/Supplemental/Arial.ttf",
        # Linux
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
        if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for p in candidates:
        try:
            return ImageFont.truetype(p, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _round_thumb(img: Image.Image, w: int, h: int, radius: int) -> Image.Image:
    img = img.convert("RGB").resize((w, h), Image.LANCZOS)
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, w, h), radius=radius, fill=255)
    out = Image.new("RGB", (w, h), PANEL)
    out.paste(img, (0, 0), mask)
    return out


def _placeholder_thumb(w: int, h: int) -> Image.Image:
    img = Image.new("RGB", (w, h), BORDER)
    draw = ImageDraw.Draw(img)
    f = _font(14)
    msg = "no image"
    bbox = draw.textbbox((0, 0), msg, font=f)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(((w - tw) / 2, (h - th) / 2), msg, fill=MUTED, font=f)
    return img


def _draw_truncated(
    draw: ImageDraw.ImageDraw,
    xy: tuple[int, int],
    text: str,
    font,
    max_width: int,
    fill,
) -> None:
    if not text:
        return
    if draw.textlength(text, font=font) <= max_width:
        draw.text(xy, text, fill=fill, font=font)
        return
    ellipsis = "…"
    e_w = draw.textlength(ellipsis, font=font)
    while text and draw.textlength(text, font=font) + e_w > max_width:
        text = text[:-1]
    draw.text(xy, text + ellipsis, fill=fill, font=font)


def _render_card_row(
    img: Image.Image,
    draw: ImageDraw.ImageDraw,
    x: int,
    y: int,
    w: int,
    card: dict,
) -> None:
    # Panel background
    draw.rounded_rectangle(
        (x, y, x + w, y + ROW_H), radius=14, outline=BORDER, fill=PANEL, width=1
    )

    # Thumbnail
    pad = (ROW_H - THUMB_H) // 2
    thumb_x, thumb_y = x + pad, y + pad
    rep = card.get("rep_path")
    pasted = False
    if rep:
        try:
            with Image.open(from_relative(rep)) as im:
                img.paste(_round_thumb(im, THUMB_W, THUMB_H, THUMB_RADIUS), (thumb_x, thumb_y))
                pasted = True
        except (FileNotFoundError, OSError):
            pass
    if not pasted:
        img.paste(_placeholder_thumb(THUMB_W, THUMB_H), (thumb_x, thumb_y))

    # Metadata
    text_x = thumb_x + THUMB_W + 24
    text_w = w - (text_x - x) - pad
    title_font = _font(28, bold=True)
    sub_font = _font(18)
    type_font = _font(14, bold=True)
    notes_font = _font(14)

    name = card.get("name") or "(unnamed)"
    name_color = FG if card.get("name") else MUTED
    cur_y = y + pad
    _draw_truncated(draw, (text_x, cur_y), name, title_font, text_w, name_color)
    cur_y += 42

    sub_parts = [
        card.get("set_name"),
        card.get("card_number"),
        str(card["year"]) if card.get("year") else None,
    ]
    sub = " · ".join(p for p in sub_parts if p) or "—"
    _draw_truncated(draw, (text_x, cur_y), sub, sub_font, text_w, MUTED)
    cur_y += 28

    type_label = (card.get("card_type") or "").upper()
    if type_label:
        _draw_truncated(draw, (text_x, cur_y), type_label, type_font, text_w, ACCENT)
        cur_y += 22

    notes = card.get("notes")
    if notes:
        _draw_truncated(draw, (text_x, cur_y), notes, notes_font, text_w, MUTED)


def _render_page(
    chunk: list[dict], page_num: int, total_pages: int, summary: dict
) -> Image.Image:
    img = Image.new("RGB", (PAGE_W, PAGE_H), BG)
    draw = ImageDraw.Draw(img)

    # Header
    draw.text((MARGIN, MARGIN), "Card Tracker — Collection", fill=FG, font=_font(36, bold=True))
    summary_text = (
        f"{summary['count']} cards · {summary['date']} · "
        f"{summary['pokemon']} pokémon · {summary['sports']} sports · {summary['other']} other"
    )
    draw.text((MARGIN, MARGIN + 50), summary_text, fill=MUTED, font=_font(16))
    line_y = MARGIN + HEADER_H - 10
    draw.line(((MARGIN, line_y), (PAGE_W - MARGIN, line_y)), fill=BORDER, width=2)

    # Card rows
    content_y = MARGIN + HEADER_H + 10
    row_w = PAGE_W - 2 * MARGIN
    for i, card in enumerate(chunk):
        _render_card_row(img, draw, MARGIN, content_y + i * (ROW_H + ROW_GAP), row_w, card)

    if not chunk:
        empty_font = _font(20)
        draw.text(
            (MARGIN, content_y + 40),
            "No cards yet — scan a binder page to start your collection.",
            fill=MUTED,
            font=empty_font,
        )

    # Footer
    foot_font = _font(13)
    foot_y = PAGE_H - MARGIN - 18
    draw.text((MARGIN, foot_y), "Generated by 10pow6 Card Tracker", fill=MUTED, font=foot_font)
    page_text = f"Page {page_num} / {total_pages}"
    draw.text(
        (PAGE_W - MARGIN - draw.textlength(page_text, font=foot_font), foot_y),
        page_text,
        fill=MUTED,
        font=foot_font,
    )

    return img


def _fetch_cards() -> list[dict]:
    sql = """
    SELECT id, name, set_name, card_number, year, card_type, notes,
           representative_crop_path
    FROM core_card
    ORDER BY
      CASE WHEN name IS NULL THEN 1 ELSE 0 END,
      LOWER(COALESCE(name, '')),
      LOWER(COALESCE(set_name, '')),
      card_number,
      created_at
    """
    with closing(connect()) as conn:
        rows = conn.execute(sql).fetchall()
    return [
        {
            "id": r["id"],
            "name": r["name"],
            "set_name": r["set_name"],
            "card_number": r["card_number"],
            "year": r["year"],
            "card_type": r["card_type"],
            "notes": r["notes"],
            "rep_path": r["representative_crop_path"],
        }
        for r in rows
    ]


def render_collection_pdf(out_path: Path) -> Path:
    """Render every CORE row to a multi-page PDF at `out_path`. Returns the path."""
    cards = _fetch_cards()
    counts = {"pokemon": 0, "sports": 0, "other": 0}
    for c in cards:
        t = (c.get("card_type") or "other").lower()
        counts[t if t in counts else "other"] += 1
    summary = {
        "count": len(cards),
        "date": datetime.utcnow().strftime("%Y-%m-%d"),
        **counts,
    }

    chunks = [cards[i : i + ROWS_PER_PAGE] for i in range(0, len(cards), ROWS_PER_PAGE)] or [[]]
    pages = [
        _render_page(chunk, i + 1, len(chunks), summary) for i, chunk in enumerate(chunks)
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    pages[0].save(
        out_path,
        save_all=True,
        append_images=pages[1:],
        format="PDF",
        resolution=150.0,
    )
    return out_path
